schema: mindbender-core:config-1.0

apps:
  - name: maya2016
  - name: nuke10

tasks:
  - label: animation
    name: animation

  - label: modeling
    name: modeling

  - label: rigging
    name: rigging

  - label: lookdev
    name: lookdev

template:
    work: "{projectpath}/f02_prod/{silo}/{asset}/work/{task}/{user}/{app}"
    publish: "{projectpath}/f02_prod/{silo}/{asset}/publish/{subset}/{version}"
