schema: mindbender-core:config-1.0

metadata:
  fps: 25
  resolution_width: 1920
  resolution_height: 1080

apps:
  - name: maya2016
  - name: nuke10
  - name: dontexist
  - name: python
    args: [-u, -c, print('Something nice')]

tasks:
  - label: Animation
    name: animation

  - label: Model
    name: modeling

  - label: Character Rigging
    name: rigging

  - label: Look Development
    name: lookdev

template:
    work: "{projectpath}/{silo}/{asset}/work/{task}/{user}/{app}"
    publish: "{projectpath}/{silo}/{asset}/publish/{subset}/{version}/{subset}.{representation}"
