schema: mindbender-core:inventory-1.0

assets:
  "Bruce":
  "Batman":
  "Camera":
  "Tarantula":

film:
  "1000":
    edit_in: 1000
    edit_out: 1143

  "1200":
    edit_in: 1000
    edit_out: 1081

  "2000":
  "2100":
  "2400":
